apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfunction-revision-controller
  namespace: openfunction
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfunction-revision-controller-leader-election-role
  namespace: openfunction
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openfunction-revision-controller-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfunction-revision-controller-leader-election-rolebinding
  namespace: openfunction
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfunction-revision-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: openfunction-revision-controller
    namespace: openfunction
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openfunction-revision-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfunction-revision-controller-role
subjects:
  - kind: ServiceAccount
    name: openfunction-revision-controller
    namespace: openfunction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: openfunction-revision-controller
    app.kubernetes.io/version: latest
    control-plane: revision-controller
  name: openfunction-revision-controller
  namespace: openfunction
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: revision-controller
  template:
    metadata:
      labels:
        control-plane: revision-controller
    spec:
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --zap-log-level=info
          command:
            - /revision-controller
          image: openfunction/revision-controller:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: revision-controller
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: openfunction-revision-controller
      terminationGracePeriodSeconds: 10
